# Generated by Django 4.0.4 on 2022-04-15 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_options_remove_task_task_task_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Price',
        ),
    ]
