# Generated by Django 4.0.4 on 2022-04-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_task_cena_currency_alter_task_cena'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewsTitle', models.CharField(max_length=50, verbose_name='Название')),
                ('AboutNews', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
