# Generated by Django 4.0.4 on 2022-04-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
